imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: main/framework.yml }
    - { resource: main/twig.yml }
    - { resource: main/assetic.yml }
    - { resource: main/doctrine.yml }
    - { resource: main/swiftmailer.yml }
    - { resource: bundles/fos_user.yml }



